# This is a basic workflow to help you get started with Actions

name: deploy to asd server

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Deploy on Self-Hosted Runner
    # The type of runner that the job will run on
    runs-on: self-hosted
    
    defaults:
      run:
        working-directory: /home/fireforce

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      # Runs a single command using the runners shell
      - name: Run git pull
        run: git pull -f

      # Runs a set of commands using the runners shell
      - name: Restart server
        run: /root/.nvm/versions/node/v17.2.0/bin/pm2 restart fireforce
